defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "modern"
      disqus:
        shortname: dirtanddistance
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "modern"
      disqus:
        shortname: dirtanddistance
